# Generated by Django 4.2.7 on 2023-12-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyblioteca', '0003_rename_lancado_em_livros_data_de_lancamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
