# Generated by Django 4.2.7 on 2023-12-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyblioteca', '0004_livros_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autore'},
        ),
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name': 'Livro'},
        ),
    ]
