# Generated by Django 4.2.7 on 2023-12-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyblioteca', '0005_alter_autor_options_alter_livros_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='capa',
            field=models.ImageField(blank=True, upload_to='livros/capas/%Y/%m/%d/'),
        ),
    ]
