# Generated by Django 4.2.7 on 2023-12-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('pyblioteca', '0006_alter_livros_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='capa',
            field=models.ImageField(upload_to='livros/capas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
