# Generated by Django 4.2.7 on 2023-12-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('pyblioteca', '0007_livros_usuario_alter_livros_capa_alter_livros_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='usuario',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
